#!/bin/bash

# i3
sudo apt-get install -y i3 i3-wm

# Audio Control
sudo apt-get install -y amixer

# Bluetooth Control
sudo apt-get install -y bluetoothctl blueman

# Brightness Control
sudo apt-get install -y brightnessctl
sudo chmod +s $(which brightnessctl)
