#!/bin/bash

# i3
sudo apt-get install -y i3 i3-wm

# polybar
sudo apt-get install -y polybar

# dmenu
sudo apt-get install -y rofi

# wallpaper
sudo apt-get install -y feh

# Audio Control
sudo apt-get install -y amixer

# Bluetooth Control
sudo apt-get install -y bluetoothctl blueman

# Brightness Control
sudo apt-get install -y brightnessctl
sudo chmod +s $(which brightnessctl)
