#!/bin/bash 

# https://www.reddit.com/r/vim/comments/1lod6kp/comment/n0stgsc/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

markdown "$@" | w3m -T text/html
